package(default_visibility = ["//visibility:public"])

load("@thunderscope_deps//:requirements.bzl", "requirement")

py_library(
    name = "pass_gen",
    srcs = ["pass_gen.py"],
    deps = [
        requirement("pyqtgraph"),
    ],
)
